import { useMemo } from 'react'
import jsPDF from 'jspdf'
import { buildTimeSeries } from '../lib/dataUtils.js'

const AI_STORAGE_KEY = 'datalytics_ai_insights'

export default function ReportStep({
  dataset,
  datasetProfile,
  predictionStatus,
  vizConfig,
  savedCharts,
  onComplete,
  onJumpToUpload,
}) {
  if (!dataset || !datasetProfile) {
    return (
      <div className="empty-state">
        <h2>Upload a dataset to generate reports</h2>
        <p>Reports include charts, insights, and model performance.</p>
        <button className="btn btn-primary" type="button" onClick={onJumpToUpload}>Go to Upload</button>
      </div>
    )
  }

  const reportText = useMemo(() => {
    const lines = []
    const aiInsights = readAiInsights()
    const salesTrend = computeSalesTrend(dataset, datasetProfile)

    lines.push('DATALYTICS ANALYTICS REPORT')
    lines.push('')
    lines.push('Dataset Overview')
    lines.push(`Name: ${dataset.name}`)
    lines.push(`Rows: ${datasetProfile.rowCount.toLocaleString()}`)
    lines.push(`Columns: ${datasetProfile.columnCount}`)
    lines.push(`Numeric columns: ${datasetProfile.numericColumns.length}`)
    lines.push(`Missing values: ${datasetProfile.missingTotal}`)
    lines.push('')
    lines.push('EDA Summary')
    lines.push(`Null percentage: ${datasetProfile.rowCount && datasetProfile.columnCount ? ((datasetProfile.missingTotal / (datasetProfile.rowCount * datasetProfile.columnCount)) * 100).toFixed(1) : 0}%`)
    lines.push(`Top numeric columns: ${datasetProfile.numericColumns.slice(0, 5).join(', ') || 'None'}`)
    lines.push(`Top categorical columns: ${datasetProfile.categoricalColumns.slice(0, 5).join(', ') || 'None'}`)
    lines.push('')
    lines.push('Visualization Summary')
    if (savedCharts?.length) {
      lines.push(`Pinned charts: ${savedCharts.map((c) => c.title).join('; ')}`)
    } else if (vizConfig?.x && vizConfig?.y) {
      lines.push(`Current focus: ${vizConfig.chartType} chart of ${vizConfig.y} vs ${vizConfig.x}`)
    } else {
      lines.push('No custom charts saved yet.')
    }
    lines.push('')
    lines.push('Prediction Results')
    lines.push(`Task type: ${predictionStatus?.preprocess_data?.task_type || 'Not available'}`)
    lines.push(`Supervised models trained: ${predictionStatus?.supervised_done ? 'Yes' : 'No'}`)
    lines.push(`Unsupervised models trained: ${predictionStatus?.unsupervised_done ? 'Yes' : 'No'}`)
    lines.push(`Best model: ${predictionStatus?.best_model_name || 'Not selected'}`)
    lines.push('')
    lines.push('AI Insights')
    if (aiInsights?.summary || aiInsights?.exec_summary) {
      lines.push(`Executive summary: ${aiInsights.summary || aiInsights.exec_summary}`)
    } else {
      lines.push('Executive summary pending. Generate insights in step 06.')
    }
    if (aiInsights?.insights?.length) {
      lines.push(`Key insights: ${aiInsights.insights.slice(0, 3).map((item) => item?.message || item).join(' | ')}`)
    }
    if (aiInsights?.recommendations?.length) {
      lines.push(`Recommendations: ${aiInsights.recommendations.slice(0, 2).map((item) => item?.action || item).join(' | ')}`)
    } else if (aiInsights?.quality_recs?.length) {
      lines.push(`Quality recommendations: ${aiInsights.quality_recs.slice(0, 2).join(' | ')}`)
    }
    if (aiInsights?.predictions?.length) {
      lines.push(`Predictions: ${aiInsights.predictions.slice(0, 2).map((item) => item?.forecast || item).join(' | ')}`)
    }
    lines.push('')
    lines.push('Sales Trend Report')
    lines.push(salesTrend)
    lines.push('')
    lines.push('Report generated by Datalytics Analytics Pipeline.')
    return lines.join('\n')
  }, [dataset, datasetProfile, predictionStatus, vizConfig, savedCharts])

  function handleDownloadPdf() {
    const doc = new jsPDF()
    const textLines = doc.splitTextToSize(reportText, 180)
    doc.text(textLines, 12, 16)
    doc.save('datalytics-report.pdf')
    onComplete('reports')
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(reportText)
    onComplete('reports')
  }

  return (
    <div className="report-container">
      <div className="report-header">
        <div>
          <h2 className="report-title">Reports</h2>
          <p className="report-subtitle">Auto-generated narrative report from all pipeline steps.</p>
        </div>
        <div className="report-download-group">
          <button type="button" className="btn btn-secondary" onClick={handleCopy}>Copy to Clipboard</button>
          <button type="button" className="btn btn-primary" onClick={handleDownloadPdf}>Download as PDF</button>
        </div>
      </div>

      <div className="report-preview">
        <pre>{reportText}</pre>
      </div>

      <div className="report-stats-grid">
        <div className="report-stat-card">
          <div className="report-stat-label">Rows</div>
          <div className="report-stat-val">{datasetProfile.rowCount.toLocaleString()}</div>
        </div>
        <div className="report-stat-card">
          <div className="report-stat-label">Columns</div>
          <div className="report-stat-val">{datasetProfile.columnCount}</div>
        </div>
        <div className="report-stat-card">
          <div className="report-stat-label">Missing</div>
          <div className="report-stat-val">{datasetProfile.missingTotal}</div>
        </div>
        <div className="report-stat-card">
          <div className="report-stat-label">Best Model</div>
          <div className="report-stat-val">{predictionStatus?.best_model_name || 'Pending'}</div>
        </div>
      </div>
    </div>
  )
}

function readAiInsights() {
  if (typeof window === 'undefined') return null
  const raw = localStorage.getItem(AI_STORAGE_KEY)
  if (!raw) return null
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

function computeSalesTrend(dataset, datasetProfile) {
  const salesColumn = datasetProfile.columns.find((col) => /sales/i.test(col))
  const dateColumn = datasetProfile.columns.find(
    (col) => datasetProfile.types[col] === 'date' || /date|month|year/i.test(col)
  )

  if (!salesColumn || !dateColumn) {
    return 'Sales trend analysis requires date and sales columns.'
  }

  const series = buildTimeSeries(dataset.rows, dateColumn, salesColumn, 8)
  if (series.length < 2) {
    return 'Not enough time series data to determine sales trend.'
  }

  const last = series[series.length - 1]
  const prev = series[series.length - 2]
  const delta = prev.value === 0 ? 0 : ((last.value - prev.value) / prev.value) * 100
  const direction = delta < 0 ? 'down' : 'up'
  return `Sales are ${direction} ${Math.abs(delta).toFixed(1)}% compared to the previous period (${prev.label} to ${last.label}).`
}
